[phases.setup]
  nixPkgs = ['nodejs_18', 'chromium']

[phases.install]
  cmds = ['npm ci']

[phases.build]
  cmds = ['echo "Build complete"']

[start]
  cmd = 'npm start'

[variables]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
  PUPPETEER_EXECUTABLE_PATH = '/nix/store/$(nix eval --raw nixpkgs#chromium.outPath)/bin/chromium'
